version: '3.8'
services:
  catinyuaa-app:
    image: catinyuaa
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:mariadb://catinyuaa-mariadb:3306/catinyuaa?useLegacyDatetimeCode=false&serverTimezone=UTC
      - JHIPSTER_CACHE_REDIS_SERVER=redis://catinyuaa-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      # - JHIPSTER_CACHE_REDIS_SERVER=redis://catinyuaa-redis:6379
      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
      - JHIPSTER_SLEEP=100 # gives time for mariadb server to start
      - SPRING_DATA_JEST_URI=http://catinyuaa-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://catinyuaa-elasticsearch:9200
    ports:
      - 10500:10500
  catinyuaa-mariadb:
    extends:
      file: mariadb.yml
      service: catinyuaa-mariadb
  catinyuaa-redis:
    extends:
      file: redis.yml
      service: catinyuaa-redis
  catinyuaa-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: catinyuaa-elasticsearch
#  jhipster-registry:
#    extends:
#      file: jhipster-registry.yml
#      service: jhipster-registry
#    environment:
#      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
#      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
