version: '2'
services:
  catinyuaa-app:
    extends:
      file: catiny-uaa.yml
      service: catinyuaa-app
  catinyuaa-mariadb:
    extends:
      file: mariadb.yml
      service: catinyuaa-mariadb
  catinyuaa-redis:
    extends:
      file: redis.yml
      service: catinyuaa-redis
  catinyuaa-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: catinyuaa-elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
