version: '3.8'
services:
  catinyuaa-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.8
    # volumes:
    #     - ~/volumes/jhipster/CatinyUAA/elasticsearch/:/usr/share/elasticsearch/data/
    ports:
      - 14500:9200
      - 14501:9300
    environment:
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'
      - 'discovery.type=single-node'
