version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    ports:
      - 10401:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:5.5.0
    ports:
      - 10400:10400
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: LISTENER_PRIVATE://localhost:9092,LISTENER_PUBLIC://103.142.139.174:10400
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_PRIVATE:PLAINTEXT,LISTENER_PUBLIC:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_PRIVATE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
