version: '2'
services:
  catinyuaa-app:
    extends:
      file: catiny-uaa.yml
      service: catinyuaa-app
  catinyuaa-mariadb:
    extends:
      file: mariadb.yml
      service: catinyuaa-mariadb
  catinyuaa-redis:
    extends:
      file: redis.yml
      service: catinyuaa-redis
  catinyuaa-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: catinyuaa-elasticsearch
#  jhipster-registry:
#    extends:
#      file: jhipster-registry.yml
#      service: jhipster-registry
#    environment:
#      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
#      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
